name: Build and Deploy

on:
  push:
    branches:
      - main  # Triggere diesen Workflow nur bei Pushes auf den main-Branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Version von Node.js, die verwendet werden soll

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()  # Deploy nur wenn der Build erfolgreich war
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git checkout gh-pages  # Annahme: Du hast eine gh-pages-Branch für Deployment
          git rm -rf .
          git checkout main -- build  # Kopiere den Build-Ordner in die gh-pages-Branch
          mv build/* .
          rm -r build

          git add .
          git commit -m "Deployed latest build to GitHub Pages"
          git push origin gh-pages  # Pushe Änderungen zur gh-pages-Branch

