name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: List branches
        run: |
          git branch -a

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin gh-pages:gh-pages  # Fetch gh-pages branch from remote
          git checkout gh-pages  # Switch to gh-pages branch
          git rm -rf .
          git checkout main -- build  # Copy build artifacts from main branch
          mv build/* .
          rm -r build
          
          git add .
          git commit -m "Deploy latest build to GitHub Pages"
          git push origin gh-pages  # Push changes to gh-pages branch
